create table public.workouts (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  source text not null check (source in ('generated', 'manual')),
  title text not null,
  status text not null default 'draft'
    check (status in ('draft', 'active', 'completed', 'archived')),
  requested_duration_minutes integer
    check (requested_duration_minutes is null or requested_duration_minutes between 5 and 45),
  engine_version text,
  profile_version bigint,
  generation_request_snapshot jsonb
    check (generation_request_snapshot is null or jsonb_typeof(generation_request_snapshot) = 'object'),
  version bigint not null default 1 check (version > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.workout_items (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  workout_id uuid not null references public.workouts (id) on delete cascade,
  position integer not null check (position > 0),
  exercise_id uuid not null references public.exercises (id) on delete restrict,
  sets integer not null check (sets between 1 and 5),
  reps integer check (reps is null or reps between 1 and 50),
  hold_seconds integer check (hold_seconds is null or hold_seconds between 1 and 600),
  rest_seconds integer not null check (rest_seconds between 0 and 300),
  compatibility_snapshot jsonb not null check (jsonb_typeof(compatibility_snapshot) = 'object'),
  version bigint not null default 1 check (version > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (workout_id, position),
  check ((reps is not null) <> (hold_seconds is not null))
);

create table public.workout_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  workout_id uuid not null references public.workouts (id) on delete cascade,
  client_request_id uuid not null,
  state text not null default 'active'
    check (state in ('active', 'paused', 'resting', 'completed', 'cancelled')),
  started_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz,
  pause_data jsonb not null default '{}'::jsonb check (jsonb_typeof(pause_data) = 'object'),
  rest_data jsonb not null default '{}'::jsonb check (jsonb_typeof(rest_data) = 'object'),
  end_reason text,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  version bigint not null default 1 check (version > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, client_request_id),
  check ((state in ('completed', 'cancelled')) = (ended_at is not null))
);

create table public.exercise_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  workout_session_id uuid not null references public.workout_sessions (id) on delete cascade,
  workout_item_id uuid references public.workout_items (id) on delete cascade,
  exercise_id uuid not null references public.exercises (id) on delete restrict,
  state text not null default 'pending'
    check (state in ('pending', 'active', 'paused', 'resting', 'completed', 'cancelled', 'skipped')),
  target_snapshot jsonb not null check (jsonb_typeof(target_snapshot) = 'object'),
  completed_reps integer not null default 0 check (completed_reps >= 0),
  completed_sets integer not null default 0 check (completed_sets >= 0),
  tracking_profile_version integer,
  started_at timestamptz,
  ended_at timestamptz,
  version bigint not null default 1 check (version > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (workout_session_id, workout_item_id),
  check ((state in ('completed', 'cancelled', 'skipped')) = (ended_at is not null))
);

create table public.metric_batches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  exercise_session_id uuid not null references public.exercise_sessions (id) on delete cascade,
  batch_id uuid not null,
  request_hash text not null check (request_hash ~ '^[a-f0-9]{64}$'),
  rep_count integer not null check (rep_count between 0 and 100),
  received_at timestamptz not null default timezone('utc', now()),
  unique (exercise_session_id, batch_id)
);

create table public.rep_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  exercise_session_id uuid not null references public.exercise_sessions (id) on delete cascade,
  metric_batch_id bigint not null references public.metric_batches (id) on delete restrict,
  set_number integer not null check (set_number between 1 and 5),
  rep_number integer not null check (rep_number between 1 and 50),
  counted boolean not null default true,
  duration_ms integer check (duration_ms is null or duration_ms between 0 and 3600000),
  range_of_motion_deg numeric(7, 2) check (range_of_motion_deg is null or range_of_motion_deg between 0 and 360),
  target_position_reached boolean,
  accuracy_score numeric(5, 2) check (accuracy_score is null or accuracy_score between 0 and 100),
  control_score numeric(5, 2) check (control_score is null or control_score between 0 and 100),
  stability_score numeric(5, 2) check (stability_score is null or stability_score between 0 and 100),
  form_score numeric(5, 2) check (form_score is null or form_score between 0 and 100),
  tracking_confidence numeric(4, 3) check (tracking_confidence is null or tracking_confidence between 0 and 1),
  feedback_codes text[] not null default '{}',
  recorded_offset_ms integer check (recorded_offset_ms is null or recorded_offset_ms between 0 and 86400000),
  created_at timestamptz not null default timezone('utc', now()),
  unique (exercise_session_id, set_number, rep_number)
);

create table public.exercise_session_summaries (
  exercise_session_id uuid primary key references public.exercise_sessions (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  target_reps integer not null check (target_reps >= 0),
  counted_reps integer not null check (counted_reps >= 0),
  overall_score numeric(5, 2) check (overall_score is null or overall_score between 0 and 100),
  analysis jsonb not null check (jsonb_typeof(analysis) = 'object'),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.session_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  workout_session_id uuid not null references public.workout_sessions (id) on delete cascade,
  exercise_session_id uuid references public.exercise_sessions (id) on delete cascade,
  event_type text not null,
  from_state text,
  to_state text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  occurred_at timestamptz not null default timezone('utc', now())
);

create table public.daily_progress (
  user_id uuid not null references auth.users (id) on delete cascade,
  activity_date date not null,
  session_count integer not null default 0 check (session_count >= 0),
  exercise_count integer not null default 0 check (exercise_count >= 0),
  set_count integer not null default 0 check (set_count >= 0),
  rep_count integer not null default 0 check (rep_count >= 0),
  active_seconds integer not null default 0 check (active_seconds >= 0),
  average_score numeric(5, 2) check (average_score is null or average_score between 0 and 100),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, activity_date)
);

comment on table public.metric_batches is 'Idempotent derived-metric batches; no raw camera data is accepted.';
comment on table public.rep_metrics is 'Derived per-repetition metrics only; no images, landmarks, coordinates, or audio.';
comment on table public.daily_progress is 'Materialized daily totals for activity history and the activity grid.';

create trigger workouts_set_updated_at
before update on public.workouts
for each row execute function public.set_updated_at();

create trigger workout_items_set_updated_at
before update on public.workout_items
for each row execute function public.set_updated_at();

create trigger workout_sessions_set_updated_at
before update on public.workout_sessions
for each row execute function public.set_updated_at();

create trigger exercise_sessions_set_updated_at
before update on public.exercise_sessions
for each row execute function public.set_updated_at();

create trigger daily_progress_set_updated_at
before update on public.daily_progress
for each row execute function public.set_updated_at();
